export const SET_RECEIVED_MESSAGES = "SET_RECEIVED_MESSAGES";
export const SET_SENT_MESSAGES = "SET_SENT_MESSAGES";
export const SET_DISPLAYED_MESSAGES = " SET_DISPLAYED_MESSAGES";
export const SET_OPENED_MESSAGE = "SET_OPENED_MESSAGE";